CREATE TABLE `subscriptions` (
  `id_subscription` INT NOT NULL AUTO_INCREMENT,
  `fid_method` INT NULL,
  `subscription_user` INT NULL,
  `subscription_key` VARCHAR(12) NULL,
  `subscription_website` VARCHAR(128) NULL,
  `subscription_days` INT NULL,
  `subscription_amount` DECIMAL(7,2) NULL,
  `subscription_created` DATETIME NULL,
  `subscription_last_charged` DATETIME NULL,
  `subscription_last_attempt` DATETIME NULL,
  `subscription_next_charge` DATETIME NULL,
  `subscription_status` VARCHAR(10) NULL,
  PRIMARY KEY (`id_subscription`),
  UNIQUE INDEX `subscription_key_UNIQUE` (`subscription_key`),
  INDEX `fid_method` (`fid_method`),
  INDEX `subscription_user` (`subscription_user`),
  INDEX `subscription_key` (`subscription_key`),
  INDEX `subscription_website` (`subscription_website`),
  INDEX `subscription_days` (`subscription_days`),
  INDEX `subscription_amount` (`subscription_amount`),
  INDEX `subscription_created` (`subscription_created`),
  INDEX `subscription_last_charged` (`subscription_last_charged`),
  INDEX `subscription_last_attempt` (`subscription_last_attempt`),
  INDEX `subscription_next_charge` (`subscription_next_charge`),
  INDEX `subscription_status` (`subscription_status`)
);
