CREATE TABLE `transactions` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `fid_attempt` INT NULL,
  `fid_user` INT NULL,
  `fid_subscription` INT NULL,
  `fid_website` INT NULL,
  `fid_method` INT NULL DEFAULT -1,
  `fid_merchant` INT NULL,
  `transaction_timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction_amount` FLOAT(7,2) NULL,
  `transaction_amount_usd` FLOAT(7,2) NULL,
  `transaction_currency` VARCHAR(10) NULL,
  `transaction_id` VARCHAR(48) NULL,
  `transaction_subscription_id` VARCHAR(48) NULL,
  `transaction_user_data` TEXT NULL,
  `transaction_description` VARCHAR(128) NULL,
  PRIMARY KEY (`id_transaction`),
  UNIQUE INDEX `id_transaction_UNIQUE` (`id_transaction` ASC),
  INDEX `fid_attempt` (`fid_attempt` ASC),
  INDEX `fid_user` (`fid_user` ASC),
  INDEX `fid_subscription` (`fid_subscription` ASC),
  INDEX `fid_website` (`fid_website` ASC),
  INDEX `fid_method` (`fid_method` ASC),
  INDEX `fid_merchant` (`fid_merchant` ASC),
  INDEX `transaction_timestamp` (`transaction_timestamp` ASC),
  INDEX `transaction_amount` (`transaction_amount` ASC),
  INDEX `transaction_amount_usd` (`transaction_amount_usd` ASC),
  INDEX `transaction_currency` (`transaction_currency` ASC),
  INDEX `transaction_id` (`transaction_id` ASC),
  INDEX `transaction_subscription_id` (`transaction_subscription_id` ASC)
);
