CREATE TABLE `media` (
  `id_media` int(11) NOT NULL AUTO_INCREMENT,
  `fid_user` int(11) DEFAULT NULL,
  `fid_user_approved` int(11) DEFAULT NULL,
  `fid_area` int(11) DEFAULT NULL,
  `fid_folder` int(11) DEFAULT NULL,
  `media_status` varchar(6) DEFAULT 'QUE',
  `media_type` varchar(6) DEFAULT NULL,
  `media_area` varchar(6) DEFAULT NULL,
  `media_timestamp` timestamp NULL DEFAULT current_timestamp(),
  `media_approved` datetime DEFAULT NULL,
  `media_classification` varchar(4) DEFAULT 'PENDNG',
  `media_tags` varchar(256) DEFAULT NULL,
  `media_description` varchar(256) DEFAULT NULL,
  `media_dimension_x` int(11) DEFAULT NULL,
  `media_dimension_y` int(11) DEFAULT NULL,
  `media_orientation` char(1) DEFAULT NULL,
  `media_duration` int(11) DEFAULT 0,
  `media_count_views` int(11) DEFAULT 0,
  `media_count_downloads` int(11) DEFAULT 0,
  `media_meta` text DEFAULT NULL,
  `media_error` varchar(128) DEFAULT 'MEROK',
  PRIMARY KEY (`id_media`),
  UNIQUE KEY `id_media_UNIQUE` (`id_media`),
  KEY `fid_user` (`fid_user`),
  KEY `fid_user_approved` (`fid_user_approved`),
  KEY `fid_area` (`fid_area`),
  KEY `fid_folder` (`fid_folder`),
  KEY `media_status` (`media_status`),
  KEY `media_type` (`media_type`),
  KEY `media_area` (`media_area`),
  KEY `media_timestamp` (`media_timestamp`),
  KEY `media_timestamp_desc` (`media_timestamp` DESC),
  KEY `media_approved` (`media_approved`),
  KEY `media_classification` (`media_classification`),
  KEY `media_count_views` (`media_count_views`),
  KEY `media_count_views_desc` (`media_count_views` DESC),
  KEY `media_count_downloads` (`media_count_downloads`),
  KEY `media_count_downloads_desc` (`media_count_downloads` DESC),
  KEY `media_error` (`media_error`),
  FULLTEXT KEY `media_tags` (`media_tags`),
  FULLTEXT KEY `media_description` (`media_description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
