CREATE TABLE `entities` (
  `id_entity` int(11) NOT NULL AUTO_INCREMENT,
  `fid_user` int(11) DEFAULT NULL,
  `fid_user_approved` int(11) DEFAULT NULL,
  `fid_contact` int(11) DEFAULT NULL,
  `fid_time` int(11) DEFAULT NULL,
  `fid_media_profile` int(11) DEFAULT NULL,
  `fid_media_cover` int(11) DEFAULT NULL,
  `entity_status` varchar(4) DEFAULT NULL,
  `entity_type` varchar(4) DEFAULT NULL,
  `entity_name` varchar(128) DEFAULT NULL,
  `entity_description` text DEFAULT NULL,
  `entity_score` decimal(4,2) DEFAULT NULL,
  `entity_count_users` int(11) DEFAULT NULL,
  `entity_count_media` int(11) DEFAULT NULL,
  `entity_count_views` varchar(45) DEFAULT NULL,
  `entity_count_score` int(11) DEFAULT NULL,
  `entity_created` timestamp NULL DEFAULT current_timestamp(),
  `entity_updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id_entity`),
  KEY `fid_user` (`fid_user`),
  KEY `fid_user_approved` (`fid_user_approved`),
  KEY `fid_contact` (`fid_contact`),
  KEY `fid_time` (`fid_time`),
  KEY `fid_media_profile` (`fid_media_profile`),
  KEY `fid_media_cover` (`fid_media_cover`),
  KEY `entity_status` (`entity_status`),
  KEY `entity_type` (`entity_type`),
  KEY `entity_score` (`entity_score`),
  KEY `entity_count_users` (`entity_count_users`),
  KEY `entity_count_media` (`entity_count_media`),
  KEY `entity_count_views` (`entity_count_views`),
  KEY `entity_count_score` (`entity_count_score`),
  KEY `entity_updated` (`entity_updated`),
  FULLTEXT KEY `entity_name` (`entity_name`),
  FULLTEXT KEY `entity_description` (`entity_description`)
);
