CREATE TABLE `users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `fid_media_profile` int(11) DEFAULT NULL,
  `fid_media_cover` int(11) DEFAULT NULL,
  `fid_verification` int(11) DEFAULT NULL,
  `user_status` char(2) DEFAULT 'PC',
  `user_level` tinyint(4) DEFAULT 0,
  `user_username` varchar(64) NOT NULL,
  `user_gender` varchar(4) DEFAULT 'M',
  `user_dob` datetime DEFAULT NULL,
  `user_city` varchar(64) DEFAULT NULL,
  `user_state` varchar(64) DEFAULT NULL,
  `user_postal` varchar(64) DEFAULT NULL,
  `user_country` varchar(3) DEFAULT NULL,
  `user_latitude` decimal(10,8) DEFAULT 0.00000000,
  `user_longitude` decimal(10,8) DEFAULT 0.00000000,
  `user_joined` datetime DEFAULT '0000-00-00 00:00:00',
  `user_login` datetime DEFAULT '0000-00-00 00:00:00',
  `user_expires` date DEFAULT '0000-00-00',
  `user_verified` datetime DEFAULT '0000-00-00 00:00:00',
  `user_age_min` tinyint(4) DEFAULT 0,
  `user_age_max` tinyint(4) DEFAULT 100,
  `user_popularity` int(11) DEFAULT 999999,
  `user_count_images` int(11) DEFAULT 0,
  `user_count_videos` int(11) DEFAULT 0,
  `user_count_views` int(11) DEFAULT 0,
  `user_count_forum` int(11) DEFAULT 0,
  `user_score` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`id_user`),
  UNIQUE KEY `id_user_UNIQUE` (`id_user`),
  UNIQUE KEY `user_username_UNIQUE` (`user_username`),
  KEY `fid_media_profile` (`fid_media_profile`),
  KEY `fid_media_cover` (`fid_media_cover`),
  KEY `fid_verification` (`fid_verification`),
  KEY `user_status` (`user_status`),
  KEY `user_level` (`user_level`),
  KEY `user_username` (`user_username`),
  KEY `user_gender` (`user_gender`),
  KEY `user_dob` (`user_dob`),
  KEY `user_city` (`user_city`),
  KEY `user_state` (`user_state`),
  KEY `user_postal` (`user_postal`),
  KEY `user_country` (`user_country`),
  KEY `user_latitude` (`user_latitude`),
  KEY `user_longitude` (`user_longitude`),
  KEY `user_joined` (`user_joined`),
  KEY `user_joined_desc` (`user_joined` DESC),
  KEY `user_login` (`user_login`),
  KEY `user_login_desc` (`user_login` DESC),
  KEY `user_expires` (`user_expires`),
  KEY `user_verified` (`user_verified`),
  KEY `user_verified_desc` (`user_verified` DESC),
  KEY `user_age_min` (`user_age_min`),
  KEY `user_age_min_desc` (`user_age_min` DESC),
  KEY `user_age_max` (`user_age_max`),
  KEY `user_age_max_desc` (`user_age_max` DESC),
  KEY `user_popularity` (`user_popularity`),
  KEY `user_popularity_desc` (`user_popularity` DESC),
  KEY `user_count_images` (`user_count_images`),
  KEY `user_count_images_desc` (`user_count_images` DESC),
  KEY `user_count_videos` (`user_count_videos`),
  KEY `user_count_videos_desc` (`user_count_videos` DESC),
  KEY `user_count_forum` (`user_count_forum`),
  KEY `user_count_forum_desc` (`user_count_forum` DESC),
  KEY `user_score` (`user_score`),
  KEY `user_score_desc` (`user_score` DESC)  
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



CREATE TABLE `users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `fid_media_profile` int(11) DEFAULT NULL,
  `fid_media_cover` int(11) DEFAULT NULL,
  `fid_verification` int(11) DEFAULT NULL,
  `user_status` char(2) DEFAULT 'PC',
  `user_level` tinyint(4) DEFAULT 0,
  `user_username` varchar(64) NOT NULL,
  `user_gender` varchar(4) DEFAULT 'M',
  `user_dob` datetime DEFAULT NULL,
  `user_city` varchar(64) DEFAULT NULL,
  `user_state` varchar(64) DEFAULT NULL,
  `user_postal` varchar(64) DEFAULT NULL,
  `user_country` varchar(3) DEFAULT NULL,
  `user_latitude` decimal(10,8) DEFAULT 0.00000000,
  `user_longitude` decimal(10,8) DEFAULT 0.00000000,
  `user_joined` datetime DEFAULT '0000-00-00 00:00:00',
  `user_login` datetime DEFAULT '0000-00-00 00:00:00',
  `user_expires` date DEFAULT '0000-00-00',
  `user_cancelled` datetime DEFAULT '0000-00-00 00:00:00',
  `user_verified` datetime DEFAULT '0000-00-00 00:00:00',
  `user_age_min` tinyint(4) DEFAULT 0,
  `user_age_max` tinyint(4) DEFAULT 100,
  `user_popularity` int(11) DEFAULT 999999,
  `user_count_images` int(11) DEFAULT 0,
  `user_count_videos` int(11) DEFAULT 0,
  `user_count_views` int(11) DEFAULT 0,
  `user_count_forum` int(11) DEFAULT 0,
  `user_score` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`id_user`),
  UNIQUE KEY `id_user_UNIQUE` (`id_user`),
  UNIQUE KEY `user_username_UNIQUE` (`user_username`),
  KEY `fid_media_profile` (`fid_media_profile`),
  KEY `fid_media_cover` (`fid_media_cover`),
  KEY `fid_verification` (`fid_verification`),
  KEY `user_status` (`user_status`),
  KEY `user_level` (`user_level`),
  KEY `user_username` (`user_username`),
  KEY `user_gender` (`user_gender`),
  KEY `user_city` (`user_city`),
  KEY `user_state` (`user_state`),
  KEY `user_postal` (`user_postal`),
  KEY `user_country` (`user_country`),
  KEY `user_latitude` (`user_latitude`),
  KEY `user_longitude` (`user_longitude`),
  KEY `user_joined` (`user_joined`),
  KEY `user_joined_desc` (`user_joined` DESC),
  KEY `user_login` (`user_login`),
  KEY `user_login_desc` (`user_login` DESC),
  KEY `user_expires` (`user_expires`),
  KEY `user_cancelled` (`user_cancelled`),
  KEY `user_verified` (`user_verified`),
  KEY `user_verified_desc` (`user_verified` DESC),
  KEY `user_age_min` (`user_age_min`),
  KEY `user_age_min_desc` (`user_age_min` DESC),
  KEY `user_age_max` (`user_age_max`),
  KEY `user_age_max_desc` (`user_age_max` DESC),
  KEY `user_popularity` (`user_popularity`),
  KEY `user_popularity_desc` (`user_popularity` DESC),
  KEY `user_count_images` (`user_count_images`),
  KEY `user_count_images_desc` (`user_count_images` DESC),
  KEY `user_count_videos` (`user_count_videos`),
  KEY `user_count_videos_desc` (`user_count_videos` DESC),
  KEY `user_count_forum` (`user_count_forum`),
  KEY `user_count_forum_desc` (`user_count_forum` DESC),
  KEY `user_score` (`user_score`),
  KEY `user_score_desc` (`user_score` DESC),
  KEY `user_dob` (`user_dob`),
  CONSTRAINT `fk_users_fid_media_cover` FOREIGN KEY (`fid_media_cover`) REFERENCES `media` (`id_media`) ON DELETE SET NULL,
  CONSTRAINT `fk_users_fid_media_profile` FOREIGN KEY (`fid_media_profile`) REFERENCES `media` (`id_media`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
