ALTER TABLE `reactions`
ADD CONSTRAINT `fk_reactions_fid_user`
FOREIGN KEY (`fid_user`)
REFERENCES `users` (`id_user`)
ON DELETE CASCADE,
ADD CONSTRAINT `fk_reactions_fid_recipient`
FOREIGN KEY (`fid_recipient`)
REFERENCES `users` (`id_user`)
ON DELETE CASCADE;